### ISSUE TITLE
Remove process call to get memory information.

### ISSUE THREAD

**Issue by csampsonza** [happner/happner-2#195]
Clever brooks demo, showed the error below.  We should not be doing system calls regularly (every 10s).

https://github.com/happner/happner-2/blob/fdbce4fdd7f78e56495e6c14b67f37586ce2dfc8/lib/modules/system/index.js#L145

```
2019-07-11 20:02:10.327 [ERROR] - 8847702ms (system) failure to produce stats { Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:538:9)
    at Object.execFile (child_process.js:221:15)
    at exec (child_process.js:152:18)
    at Object.stats (/node_js/app/node_modules/proc-stats/index.js:89:4)
    at /node_js/app/node_modules/happner-2/lib/modules/system/index.js:145:19
    at System._this.getDBFileInfo (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:93:5)
    at System._this.__getStats (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:138:12)
    at StatsService.System._this.__handleHappnStats (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:22:11)
    at StatsService.emit (events.js:189:13)
    at StatsService.EventEmitter.emit (domain.js:441:20)
    at Object.__interval.setInterval.bind.service (/node_js/app/node_modules/happn-3/lib/services/stats/service.js:49:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }
2019-07-11 20:02:10.337 [ERROR] -     at /node_js/app/node_modules/happner-2/lib/modules/system/index.js:24:38
2019-07-11 20:02:10.345 [ERROR] - Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:538:9)
    at Object.execFile (child_process.js:221:15)
    at exec (child_process.js:152:18)
    at Object.stats (/node_js/app/node_modules/proc-stats/index.js:89:4)
    at /node_js/app/node_modules/happner-2/lib/modules/system/index.js:145:19
    at System._this.getDBFileInfo (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:93:5)
    at System._this.__getStats (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:138:12)
    at StatsService.System._this.__handleHappnStats (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:22:11)
    at StatsService.emit (events.js:189:13)
    at StatsService.EventEmitter.emit (domain.js:441:20)
    at Object.__interval.setInterval.bind.service (/node_js/app/node_modules/happn-3/lib/services/stats/service.js:49:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2019-07-11 20:02:20.282 [ERROR] -  9955ms (system) failure to produce stats { Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:538:9)
    at Object.execFile (child_process.js:221:15)
    at exec (child_process.js:152:18)
    at Object.stats (/node_js/app/node_modules/proc-stats/index.js:89:4)
    at /node_js/app/node_modules/happner-2/lib/modules/system/index.js:145:19
    at System._this.getDBFileInfo (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:93:5)
    at System._this.__getStats (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:138:12)
    at StatsService.System._this.__handleHappnStats (/node_js/app/node_modules/happner-2/lib/modules/system/index.js:22:11)
    at StatsService.emit (events.js:189:13)
    at StatsService.EventEmitter.emit (domain.js:441:20)
    at Object.__interval.setInterval.bind.service (/node_js/app/node_modules/happn-3/lib/services/stats/service.js:49:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }
```

**Comment by csampsonza** [comment]
^Bump.

Seen this crash on a secure gateway.  Why do we need a system call to be run every 10s

**Comment by JensEggers** [comment]
There seems to be a deeper issue there, since the device appears to be running out of memory.

Not suggesting we have to keep the sys calls every 10s, but they should definitely not be a problem.
