### ISSUE TITLE
fix deprecated unhandled promise rejection error

### ISSUE THREAD

**Issue by JensEggers** [happner/happner-2#201]
```
2019-07-29 10:31:58.573 [ERROR] -     3ms client (HappnClient) unhandled error { Error: connect ECONNREFUSED 127.0.0.1:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 55000 }
2019-07-29 10:31:58.574 [ERROR] -     at HappnClient.handle_error (/Users/jens/git/happner-endpoint/node_modules/happn-3/lib/client.js:1170:14)
2019-07-29 10:31:58.574 [ERROR] - Error: connect ECONNREFUSED 127.0.0.1:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:19157) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    at emitWarning (internal/process/promises.js:81:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:19157) Error: connect ECONNREFUSED 127.0.0.1:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:19157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:95:13)
    at emitWarning (internal/process/promises.js:88:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

**Comment by JensEggers** [comment]
problem occurs in happner-endpoint tests: https://github.com/FieldServer/happner-endpoint/commit/f81c38141b52b84e69ad3aac673a48614c50de57
