### ISSUE TITLE
weird crypto error in happner-2@10

### ISSUE THREAD

**Issue by JensEggers** [happner/happner-2#227]
happner error (in core app v.15.1.3-tr4283-secure-gateway-24)
```
[ERROR] -    44ms goldrib_sXLTZZfj (HappnServer) : SyntaxUnexpected token X in JSON at position 0, severity: 0 system error: ProtocolService, stack: SyntaxError: Unexpected token X in JSON at position 0
    at JSON.parse (<anonymous>)
    at Crypto.symmetricDecryptObjectiv (/home/jens/git/smc-core-application/node_modules/happn-util-crypto/lib/crypto.js:94:19)
    at CryptoService.symmetricDecryptObjectiv (/home/jens/git/smc-core-application/node_modules/happn-3/lib/services/crypto/service.js:97:22)
    at ProtocolHappn4.transformIn (/home/jens/git/smc-core-application/node_modules/happn-3/lib/services/protocol/happn_4.js:46:52)
    at ProtocolService.processInboundStack (/home/jens/git/smc-core-application/node_modules/happn-3/lib/services/protocol/service.js:65:28)
    at /home/jens/git/smc-core-application/node_modules/happn-3/lib/services/protocol/service.js:258:10
```

**Comment by JensEggers** [comment]
saw this once, seems intermittent, will keep an eye on things and update issue if it recurs on v.11
