### ISSUE TITLE
Browser sessions get errors if the mesh restarts

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happner-2#261]
Happner client error 'secret must be a string and cannot be null or undefined`.

After reboot if browser was left open.

**Comment by JensEggers** [comment]
log extract:
```
2020-03-18 03:09:59.562 [ERROR] -  2364ms zircongrabber_OmDCC_WQ (HappnServer) : secret must be a string and cannot be null or undefined, severity: 0 system error: ProtocolService, stack: Error: secret must be a string and cannot be null or undefined
    at UtilsService.computeiv (/node_js/app/node_modules/happn-3/lib/services/utils/shared.js:144:13)
    at ProtocolHappn4.transformIn (/node_js/app/node_modules/happn-3/lib/services/protocol/happn_4.js:42:42)
    at ProtocolService.processInboundStack (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:74:28)
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:324:10
    at /node_js/app/node_modules/async/dist/async.js:473:16
    at next (/node_js/app/node_modules/async/dist/async.js:5329:29)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at HappnLayer.__inboundLayer (/node_js/app/node_modules/happner-2/lib/system/happn.js:293:5)
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at next (/node_js/app/node_modules/async/dist/async.js:5331:9)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:305:9
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/node_js/app/node_modules/async/dist/async.js:5334:5)
    at ProtocolService.processLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:302:9)
    at ProtocolService.processMessageInLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:322:8)
2020-03-18 03:09:59.592 [ERROR] -     at LogService.write (/node_js/app/node_modules/happn-3/lib/services/log/service.js:62:26)
2020-03-18 03:09:59.667 [ERROR] -   105ms zircongrabber_OmDCC_WQ (HappnServer) : secret must be a string and cannot be null or undefined, severity: 0 system error: ProtocolService, stack: Error: secret must be a string and cannot be null or undefined
    at UtilsService.computeiv (/node_js/app/node_modules/happn-3/lib/services/utils/shared.js:144:13)
    at ProtocolHappn4.transformIn (/node_js/app/node_modules/happn-3/lib/services/protocol/happn_4.js:42:42)
    at ProtocolService.processInboundStack (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:74:28)
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:324:10
    at /node_js/app/node_modules/async/dist/async.js:473:16
    at next (/node_js/app/node_modules/async/dist/async.js:5329:29)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at HappnLayer.__inboundLayer (/node_js/app/node_modules/happner-2/lib/system/happn.js:293:5)
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at next (/node_js/app/node_modules/async/dist/async.js:5331:9)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:305:9
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/node_js/app/node_modules/async/dist/async.js:5334:5)
    at ProtocolService.processLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:302:9)
    at ProtocolService.processMessageInLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:322:8)
2020-03-18 03:09:59.692 [ERROR] -     at LogService.write (/node_js/app/node_modules/happn-3/lib/services/log/service.js:62:26)
2020-03-18 03:10:00.752 [ERROR] -  1085ms zircongrabber_OmDCC_WQ (HappnServer) : secret must be a string and cannot be null or undefined, severity: 0 system error: ProtocolService, stack: Error: secret must be a string and cannot be null or undefined
    at UtilsService.computeiv (/node_js/app/node_modules/happn-3/lib/services/utils/shared.js:144:13)
    at ProtocolHappn4.transformIn (/node_js/app/node_modules/happn-3/lib/services/protocol/happn_4.js:42:42)
    at ProtocolService.processInboundStack (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:74:28)
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:324:10
    at /node_js/app/node_modules/async/dist/async.js:473:16
    at next (/node_js/app/node_modules/async/dist/async.js:5329:29)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at HappnLayer.__inboundLayer (/node_js/app/node_modules/happner-2/lib/system/happn.js:293:5)
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at next (/node_js/app/node_modules/async/dist/async.js:5331:9)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:305:9
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/node_js/app/node_modules/async/dist/async.js:5334:5)
    at ProtocolService.processLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:302:9)
    at ProtocolService.processMessageInLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:322:8)
2020-03-18 03:10:00.760 [ERROR] -     at LogService.write (/node_js/app/node_modules/happn-3/lib/services/log/service.js:62:26)
2020-03-18 03:10:00.947 [ INFO] -   195ms (Happn) 'admin' connected
2020-03-18 03:10:02.650 [ INFO] -  1704ms (fieldpop) Remote Services started
2020-03-18 03:10:02.718 [ERROR] -    68ms zircongrabber_OmDCC_WQ (HappnServer) : SyntaxUnexpected token Y in JSON at position 0, severity: 0 system error: ProtocolService, stack: SyntaxError: Unexpected token Y in JSON at position 0
    at JSON.parse (<anonymous>)
    at Crypto.symmetricDecryptObjectiv (/node_js/app/node_modules/happn-util-crypto/lib/crypto.js:93:19)
    at CryptoService.symmetricDecryptObjectiv (/node_js/app/node_modules/happn-3/lib/services/crypto/service.js:97:22)
    at ProtocolHappn4.transformIn (/node_js/app/node_modules/happn-3/lib/services/protocol/happn_4.js:43:52)
    at ProtocolService.processInboundStack (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:74:28)
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:324:10
    at /node_js/app/node_modules/async/dist/async.js:473:16
    at next (/node_js/app/node_modules/async/dist/async.js:5329:29)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at HappnLayer.__inboundLayer (/node_js/app/node_modules/happner-2/lib/system/happn.js:293:5)
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at next (/node_js/app/node_modules/async/dist/async.js:5331:9)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:305:9
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/node_js/app/node_modules/async/dist/async.js:5334:5)
2020-03-18 03:10:02.725 [ERROR] -     at LogService.write (/node_js/app/node_modules/happn-3/lib/services/log/service.js:62:26)
2020-03-18 03:10:02.764 [ERROR] -    42ms zircongrabber_OmDCC_WQ (HappnServer) : SyntaxUnexpected token Y in JSON at position 0, severity: 0 system error: ProtocolService, stack: SyntaxError: Unexpected token Y in JSON at position 0
    at JSON.parse (<anonymous>)
    at Crypto.symmetricDecryptObjectiv (/node_js/app/node_modules/happn-util-crypto/lib/crypto.js:93:19)
    at CryptoService.symmetricDecryptObjectiv (/node_js/app/node_modules/happn-3/lib/services/crypto/service.js:97:22)
    at ProtocolHappn4.transformIn (/node_js/app/node_modules/happn-3/lib/services/protocol/happn_4.js:43:52)
    at ProtocolService.processInboundStack (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:74:28)
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:324:10
    at /node_js/app/node_modules/async/dist/async.js:473:16
    at next (/node_js/app/node_modules/async/dist/async.js:5329:29)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at HappnLayer.__inboundLayer (/node_js/app/node_modules/happner-2/lib/system/happn.js:293:5)
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at next (/node_js/app/node_modules/async/dist/async.js:5331:9)
    at /node_js/app/node_modules/async/dist/async.js:969:16
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:305:9
    at nextTask (/node_js/app/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/node_js/app/node_modules/async/dist/async.js:5334:5)
2020-03-18 03:10:02.784 [ERROR] -     at LogService.write (/node_js/app/node_modules/happn-3/lib/services/log/service.js:62:26)
```
