### ISSUE TITLE
REST server handles login errors inconsistently, reveals valid/invalid username

### ISSUE THREAD

**Issue by JensEggers** [happner/happner-2#67]
with an unknown user name the REST response contains this:
```
 {
    "message": "Failure logging in",
    "data": null,
    "error": {
        "stack": "Error: eggersjens@gmail.co does not exist in the system\n    at /home/ubuntu/fieldpop_aws/web/app/node_modules/happn-3/lib/services/security/users.js:188:34\n    at /home/ubuntu/fieldpop_aws/web/app/node_modules/happn-3/lib/services/data/service.js:499:39\n    at /home/ubuntu/fieldpop_aws/web/app/node_modules/happn-service-mongo-2/index.js:77:5\n    at doCallback (/home/ubuntu/fieldpop_aws/web/app/node_modules/happn-service-mongo-2/lib/datastore.js:280:12)\n    at handleCallback (/home/ubuntu/fieldpop_aws/web/app/node_modules/mongodb/lib/utils.js:120:56)\n    at /home/ubuntu/fieldpop_aws/web/app/node_modules/mongodb/lib/cursor.js:860:16\n    at handleCallback (/home/ubuntu/fieldpop_aws/web/app/node_modules/mongodb-core/lib/cursor.js:171:5)\n    at setCursorNotified (/home/ubuntu/fieldpop_aws/web/app/node_modules/mongodb-core/lib/cursor.js:515:3)\n    at /home/ubuntu/fieldpop_aws/web/app/node_modules/mongodb-core/lib/cursor.js:590:16\n    at queryCallback (/home/ubuntu/fieldpop_aws/web/app/node_modules/mongodb-core/lib/cursor.js:232:18)\n    at /home/ubuntu/fieldpop_aws/web/app/node_modules/mongodb-core/lib/connection/pool.js:469:18\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)",
        "message": "eggersjens@gmail.co does not exist in the system"
    }
}
```

while a known username results in:
```
{
    "message": "Failure logging in",
    "data": null,
    "error": {
        "name": "AccessDenied",
        "code": 403,
        "message": "Invalid credentials"
    }
}
```

We want the second result all the time.

Please fix together with #66 (use correct HTTP error code on login failure)

**Comment by southbite** [comment]
This is a happn-3 issue, will update happn-3 accordingly

**Comment by southbite** [comment]
I have done the requisite work on this, but have found this does change the protocol (as all errors return code 401 as opposed to 403 in their code, and the error message has been standardised to "Invalid credentials") - so my question is, is this a breaking change? Do I have to modify protocol 1 and 2 to keep the same error settings in case the C clients expect 403 and the "does not exist in the system" error message, or do we regard this as a fix, deploy and hope for the best?

**Comment by JensEggers** [comment]
I think we should treat it as a bugfix

**Comment by JensEggers** [comment]
@southbite pls point me at the PR/commit that fixes this

**Comment by JensEggers** [comment]
fixed by https://github.com/happner/happn-3/pull/99/
